"""Helpers for parsing/normalizing Feishu messages."""

from __future__ import annotations

import json
import re
from typing import Any

from .types import FeishuChatType, FeishuIncomingMessage, FeishuMention, FeishuMessageType


def _parse_post_content(raw: str) -> str:
    """Extract text from Feishu post rich-text content."""
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return raw

    text_parts: list[str] = []
    for locale_content in parsed.values():
        if not isinstance(locale_content, dict):
            continue
        paragraphs = locale_content.get("content", [])
        if not isinstance(paragraphs, list):
            continue
        for paragraph in paragraphs:
            if not isinstance(paragraph, list):
                continue
            for element in paragraph:
                if isinstance(element, dict) and isinstance(element.get("text"), str):
                    text_parts.append(element["text"])

    return "".join(text_parts).strip() or raw


def parse_message_content(raw_content: str, msg_type: FeishuMessageType) -> str:
    """Parse Feishu content JSON to plain text for the agent."""
    if not raw_content:
        return ""

    if msg_type == FeishuMessageType.TEXT:
        try:
            parsed = json.loads(raw_content)
            if isinstance(parsed, dict) and isinstance(parsed.get("text"), str):
                return parsed["text"]
        except json.JSONDecodeError:
            pass
        return raw_content

    if msg_type == FeishuMessageType.POST:
        return _parse_post_content(raw_content)

    return raw_content


def strip_bot_mentions(content: str, mentions: list[FeishuMention], bot_open_id: str | None) -> str:
    """Strip bot mention markers from message text."""
    if not content:
        return ""

    text = content

    # Remove mention keys (e.g. @_user_1) generated by Feishu payloads.
    normalized_bot_id = (bot_open_id or "").strip()
    if normalized_bot_id:
        for mention in mentions:
            if mention.open_id and mention.open_id.strip() == normalized_bot_id:
                if mention.key:
                    text = text.replace(mention.key, "")

    # Remove generic <at ...>...</at> fragments if still present.
    text = re.sub(r"<at\s+user_id=\"[^\"]+\">[^<]*</at>", "", text)

    return text.strip()


def chunk_text(text: str, limit: int = 3000) -> list[str]:
    """Chunk long text for Feishu sending with newline preference."""
    if not text:
        return [""]
    if limit <= 0 or len(text) <= limit:
        return [text]

    chunks: list[str] = []
    remaining = text

    while len(remaining) > limit:
        split_at = remaining.rfind("\n", 0, limit)
        if split_at < int(limit * 0.5):
            split_at = limit
        chunks.append(remaining[:split_at].rstrip())
        remaining = remaining[split_at:].lstrip("\n")

    if remaining:
        chunks.append(remaining)

    return chunks


def parse_incoming_event(event_data: dict[str, Any], bot_open_id: str | None = None) -> FeishuIncomingMessage | None:
    """Parse raw Feishu event payload into normalized message object."""
    sender = event_data.get("sender")
    message = event_data.get("message")

    if not isinstance(sender, dict) or not isinstance(message, dict):
        return None

    sender_id = sender.get("sender_id") if isinstance(sender.get("sender_id"), dict) else {}

    message_id = str(message.get("message_id") or "").strip()
    chat_id = str(message.get("chat_id") or "").strip()
    if not message_id or not chat_id:
        return None

    chat_type_raw = str(message.get("chat_type") or "p2p").lower()
    msg_type_raw = str(message.get("message_type") or "text").lower()

    chat_type = FeishuChatType(chat_type_raw) if chat_type_raw in {t.value for t in FeishuChatType} else FeishuChatType.P2P
    message_type = (
        FeishuMessageType(msg_type_raw)
        if msg_type_raw in {t.value for t in FeishuMessageType}
        else FeishuMessageType.TEXT
    )

    raw_content = str(message.get("content") or "")
    content = parse_message_content(raw_content, message_type)

    mentions: list[FeishuMention] = []
    mentioned_bot = False
    for item in message.get("mentions", []) or []:
        if not isinstance(item, dict):
            continue
        mention_id = item.get("id") if isinstance(item.get("id"), dict) else {}
        mention = FeishuMention(
            key=str(item.get("key") or ""),
            name=str(item.get("name") or ""),
            open_id=mention_id.get("open_id"),
            user_id=mention_id.get("user_id"),
            union_id=mention_id.get("union_id"),
        )
        mentions.append(mention)
        if bot_open_id and mention.open_id and mention.open_id.strip() == bot_open_id.strip():
            mentioned_bot = True

    # If content still has @all, treat as explicit group trigger.
    if "@_all" in raw_content:
        mentioned_bot = True

    create_time_ms = None
    create_time_raw = message.get("create_time")
    if create_time_raw is not None:
        try:
            create_time_ms = int(str(create_time_raw))
            if create_time_ms < 1_000_000_000_000:
                create_time_ms *= 1000
        except (TypeError, ValueError):
            create_time_ms = None

    sender_open_id = str(sender_id.get("open_id") or "").strip()
    sender_user_id = str(sender_id.get("user_id") or sender_open_id).strip()

    return FeishuIncomingMessage(
        message_id=message_id,
        chat_id=chat_id,
        chat_type=chat_type,
        message_type=message_type,
        content=content,
        raw_content=raw_content,
        sender_open_id=sender_open_id,
        sender_user_id=sender_user_id,
        create_time_ms=create_time_ms,
        root_id=message.get("root_id"),
        parent_id=message.get("parent_id"),
        thread_id=message.get("thread_id"),
        mentions=mentions,
        mentioned_bot=mentioned_bot,
    )
